<?php
namespace RIS\Auction\Traits;

trait Features {
    public $all_states = [
        'Alabama'        => 'AL',
        'Alaska'         => 'AK',
        'Arizona'        => 'AZ',
        'Arkansas'       => 'AR',
        'California'     => 'CA',
        'Colorado'       => 'CO',
        'Connecticut'    => 'CT',
        'Delaware'       => 'DE',
        'Florida'        => 'FL',
        'Georgia'        => 'GA',
        'Hawaii'         => 'HI',
        'Idaho'          => 'ID',
        'Illinois'       => 'IL',
        'Indiana'        => 'IN',
        'Iowa'           => 'IA',
        'Kansas'         => 'KS',
        'Kentucky'       => 'KY',
        'Louisiana'      => 'LA',
        'Maine'          => 'ME',
        'Maryland'       => 'MD',
        'Massachusetts'  => 'MA',
        'Michigan'       => 'MI',
        'Minnesota'      => 'MN',
        'Mississippi'    => 'MS',
        'Missouri'       => 'MO',
        'Montana'        => 'MT',
        'Nebraska'       => 'NE',
        'Nevada'         => 'NV',
        'New Hampshire'  => 'NH',
        'New Jersey'     => 'NJ',
        'New Mexico'     => 'NM',
        'New York'       => 'NY',
        'North Carolina' => 'NC',
        'North Dakota'   => 'ND',
        'Ohio'           => 'OH',
        'Oklahoma'       => 'OK',
        'Oregon'         => 'OR',
        'Pennsylvania'   => 'PA',
        'Rhode Island'   => 'RI',
        'South Carolina' => 'SC',
        'South Dakota'   => 'SD',
        'Tennessee'      => 'TN',
        'Texas'          => 'TX',
        'Utah'           => 'UT',
        'Vermont'        => 'VT',
        'Virginia'       => 'VA',
        'Washington'     => 'WA',
        'West Virginia'  => 'WV',
        'Wisconsin'      => 'WI',
        'Wyoming'        => 'WY',

    ];
    // Interior
    public $interior_features      = ['2 Staircases', 'In-Law Floorplan', 'Attic Fan', 'Balcony', 'Bar', 'Beamed Ceilings', 'Block Walls', 'Brick Walls', 'Built-in Features', 'Cathedral Ceiling(s)', 'Ceiling Fan(s)', 'Ceramic Counters', 'Chair Railings', 'Coffered Ceiling(s)', 'Copper Plumbing Full', 'Copper Plumbing Partial', 'Corian Counters', 'Crown Molding', 'Dry Bar', 'Dumbwaiter', 'Electronic Air Cleaner', 'Elevator', 'Formica Counters', 'Furnished', 'Granite Counters', 'High Ceilings', 'Home Automation System', 'Intercom', 'Laminate Counters', 'Living Room Balcony', 'Living Room Deck Attached', 'Open Floorplan', 'Pantry', 'Partially Furnished', 'Phone System', 'Pull Down Stairs to Attic', 'Recessed Lighting', 'Stair Climber', 'Stone Counters', 'Storage', 'Sump Pump', 'Sunken Living Room', 'Suspended Ceiling(s)', 'Tandem', 'Tile Counters', 'Track Lighting', 'Trash Chute', 'Tray Ceiling(s)', 'Two Story Ceilings', 'Unfinished Walls', 'Unfurnished', 'Vacuum Central', 'Wainscoting', 'Wet Bar', 'Wired for Data', 'Wired for Sound', 'Wood Product Walls'];
    public $basements              = ['Finished', 'Unfinished', 'Utility'];
    public $fireplaces             = ['Bath', 'Bonus Room', 'Den', 'Dining Room', 'Family Room', 'Game Room', 'Guest House', 'Kitchen', 'Library', 'Living Room', 'Circulating', 'Master Bedroom', 'Master Retreat', 'Outside', 'Patio', 'Electric', 'Gas', 'Gas Starter', 'Pellet Stove', 'Propane', 'Wood Burning', 'Wood Stove Insert', 'Blower Fan', 'Circular', 'Decorative', 'Fire Pit', 'Free Standing', 'Great Room', 'Heatilator', 'Masonry', 'Raised Hearth', 'Zero Clearance', 'See Through', 'Two Way', 'See Remarks'];
    public $coolings               = ['Central Air', 'Dual', 'Zoned', 'Wall/Window Unit(s)', 'Evaporative Cooling', 'Heat Pump', 'Humidity Control', 'Whole House Fan', 'Electric', 'Gas', 'ENERGY STAR Qualified Equipment', 'High Efficiency', 'SEER Rated 13-15', 'SEER Rated 16+', 'See Remarks'];
    public $heatings               = ['Central', 'Zoned', 'Baseboard', 'Floor Furnace', 'Wall Furnace', 'Space Heater', 'Forced Air', 'Gravity', 'Heat Pump', 'Radiant', 'Electric', 'Natural Gas', 'Propane', 'Kerosene', 'Pellet Stove', 'Wood', 'Oil', 'Solar', 'ENERGY STAR Qualified Equipment', 'High Efficiency', 'Combination', 'Fireplace(s)', 'Humidity Control', 'Wood Stove', 'See Remarks'];
    public $accessibility_features = ['2+ Access Exits', '32 Inch Or More Wide Doors', '36 Inch Or More Wide Halls', '48 Inch Or More Wide Halls', 'Accessible Elevator Installed', 'Adaptable For Elevator', 'Customized Wheelchair Accessible', 'Disability Features', 'Doors - Swing In', 'Entry Slope Less Than 1 Foot', 'Grab Bars In Bathroom(s)', 'Low Pile Carpeting', 'Lowered Light Switches', 'No Interior Steps', 'Other', 'Parking', 'Ramp - Main Level', 'See Remarks'];
    public $kitchen_features       = ['Built-in Trash/Recycling', 'Butler’s Pantry', 'Corian Counters', 'Formica Counters', 'Granite Counters', 'Kitchen Island', 'Kitchen Open to Family Room', 'Kitchenette', 'Laminate Counters', 'Pots & Pan Drawers', 'Quartz Counters', 'Remodeled Kitchen', 'Self-closing cabinet doors', 'Self-closing drawers', 'Stone Counters', 'Tile Counters', 'Utility sink', 'Walk-In Pantry'];
    public $floorings              = ['Bamboo', 'Brick', 'Carpet', 'Concrete', 'Laminate', 'See Remarks', 'Stone', 'Tile', 'Vinyl', 'Wood'];
    public $appliances             = ['6 Burner Stove', 'Barbecue', 'Built-In Range', 'Coal Water Heater', 'Convection Oven', 'Dishwasher', 'Double Oven', 'Electric Oven', 'Electric Range', 'Electric Cooktop', 'Electric Water Heater', 'ENERGY STAR Qualified Appliances', 'ENERGY STAR Qualified Water Heater', 'Free-Standing Range', 'Freezer', 'Disposal', 'Gas & Electric Range', 'Gas Oven', 'Gas Range', 'Gas Cooktop', 'Gas Water Heater', 'Indoor Grill', 'High Efficiency Water Heater', 'Hot Water Circulator', 'Ice Maker', 'Instant Hot Water', 'Microwave', 'No Hot Water', 'Portable Dishwasher', 'Propane Oven', 'Propane Range', 'Propane Cooktop', 'Propane Water Heater', 'Range Hood', 'Recirculated Exhaust Fan', 'Refrigerator', 'Self Cleaning Oven', 'Solar Hot Water', 'Tankless Water Heater', 'Trash Compactor', 'Vented Exhaust Fan', 'Warming Drawer', 'Water Heater Central', 'Water Heater', 'Water Line to Refrigerator', 'Water Purifier', 'Water Softener'];
    public $bathroom_features      = ['Bathtub', 'Bidet', 'Low Flow Shower', 'Low Flow Toilet(s)', 'Shower', 'Shower in Tub', 'Closet in bathroom', 'Corian Counters', 'Double sinks in bath(s)', 'Double Sinks In Master Bath', 'Dual shower heads (or Multiple)', 'Exhaust fan(s)', 'Formica Counters', 'Granite Counters', 'Heated Floor', 'Hollywood Bathroom (Jack&Jill)', 'Humidity controlled', 'Jetted Tub', 'Laminate Counters', 'Linen Closet/Storage', 'Privacy toilet door', 'Quartz Counters', 'Remodeled', 'Separate tub and shower', 'Soaking Tub', 'Stone Counters', 'Tile Counters', 'Upgraded', 'Vanity area', 'Walk-in shower'];
    public $eating_areas           = ['Area', 'Breakfast Counter / Bar', 'Breakfast Nook', 'Dining Ell', 'Family Kitchen', 'In Family Room', 'Dining Room', 'In Kitchen', 'In Living Room', 'Separated', 'Country Kitchen', 'See Remarks'];
    public $electrics              = ['220 Volts For Spa', '220 Volts in Garage', '220 Volts in Kitchen', '220 Volts in Laundry', '220 Volts in Workshop', '220V Other - See Remarks', '220 Volts', '440 Volts', 'Electricity - On Bond', 'Electricity - On Property', 'Electricity - Unknown', 'Heavy', 'Photovoltaics on Grid', 'Photovoltaics Seller Owned', 'Photovoltaics Stand-Alone', 'Photovoltaics Third-Party Owned', 'Standard'];
    public $laundries              = ['Common Area', 'Community', 'Dryer Included', 'Electric Dryer Hookup', 'Gas & Electric Dryer Hookup', 'Gas Dryer Hookup', 'In Carport', 'In Closet', 'In Garage', 'In Kitchen', 'Individual Room', 'Inside', 'Laundry Chute', 'Upper Level', 'Outside', 'Propane Dryer Hookup', 'See Remarks', 'Stackable', 'Washer Hookup', 'Washer Included'];
    public $room_types             = ['All Bedrooms Down', 'All Bedrooms Up', 'Art Studio', 'Atrium', 'Attic', 'Basement', 'Bonus Room', 'Center Hall', 'Converted Bedroom', 'Dance Studio', 'Den', 'Dressing Area', 'Entry', 'Exercise Room', 'Family Room', 'Formal Entry', 'Foyer', 'Galley Kitchen', 'Game Room', 'Great Room', "Guest/Maid's Quarters", 'Home Theatre', 'Jack & Jill', 'Kitchen', 'Laundry', 'Library', 'Living Room', 'Loft', 'Main Floor Bedroom', 'Main Floor Master Bedroom', 'Master Bathroom', 'Master Bedroom', 'Master Suite', 'Media Room', 'Multi-Level Bedroom', 'Office', 'Projection', 'Recreation', 'Retreat', 'Sauna', 'See Remarks', 'Separate Family Room', 'Sound Studio', 'Sun', 'Two Masters', 'Utility Room', 'Walk-In Closet', 'Walk-In Pantry', 'Wine Cellar', 'Workshop'];
    public $utilities              = ['Cable Available', 'Cable Connected', 'Cable Not Available', 'Electricity Available', 'Electricity Connected', 'Electricity Not Available', 'Natural Gas Available', 'Natural Gas Connected', 'Natural Gas Not Available', 'Other', 'Phone Available', 'Phone Connected', 'Phone Not Available', 'Propane', 'See Remarks', 'Sewer Available', 'Sewer Connected', 'Sewer Not Available', 'Underground Utilities', 'Water Available', 'Water Connected', 'Water Not Available'];

    // Exterior

    public $pool_features            = ['None', 'Private', 'Association', 'Community', 'Above Ground', 'Black Bottom', 'Diving Board', 'Exercise Pool', 'Fenced', 'Fiberglass', 'Filtered', 'Gunite', 'Heated', 'Heated Passively', 'Electric Heat', 'Gas Heat', 'Heated with Propane', 'In Ground', 'Indoor', 'Lap', 'Infinity', 'No Permits', 'Pebble', 'Permits', 'Pool Cover', 'Roof Top', 'Salt Water', 'See Remarks', 'Solar Heat', 'Tile', 'Vinyl', 'Waterfall'];
    public $views                    = ['None', 'Back Bay', 'Dunes', 'Bay', 'Bluff', 'Bridge(s)', 'Canal', 'Canyon', 'Catalina', 'City Lights', 'Coastline', 'Courtyard', 'Creek/Stream', 'Desert', 'Golf Course', 'Harbor', 'Hills', 'Lake', 'Landmark', 'Marina', 'Meadow', 'Mountain(s)', 'Neighborhood', 'Ocean', 'Orchard', 'Panoramic', 'Park/Greenbelt', 'Pasture', 'Peek-A-Boo', 'Pier', 'Pond', 'Pool', 'Reservoir', 'River', 'Rocks', 'See Remarks', 'Trees/Woods', 'Valley', 'Vincent Thomas Bridge', 'Vineyard', 'Water', 'White Water'];
    public $door_features            = ['Atrium Doors', 'Double Door Entry', 'ENERGY STAR Qualified Doors', 'French Doors', 'Insulated Doors', 'Mirror Closet Door(s)', 'Panel Doors', 'Service Entrance', 'Sliding Doors', 'Storm Door(s)'];
    public $fencings                 = ['None', 'Average Condition', 'Barbed Wire', 'Block', 'Brick', 'Chain Link', 'Cross Fenced', 'Electric', 'Excellent Condition', 'Fair Condition', 'Glass', 'Goat Type', 'Good Condition', 'Grapestake', 'Invisible', 'Livestock', 'Masonry', 'Needs Repair', 'New Condition', 'Partial', 'Pipe', 'Poor Condition', 'Privacy', 'Redwood', 'Security', 'See Remarks', 'Split Rail', 'Stone', 'Stucco Wall', 'Vinyl', 'Wire', 'Wood', 'Wrought Iron'];
    public $security_features        = ['24 Hour Security', 'Gated with Attendant', 'Automatic Gate', 'Carbon Monoxide Detector(s)', 'Card/Code Access', 'Closed Circuit Camera(s)', 'Fire and Smoke Detection System', 'Fire Rated Drywall', 'Fire Sprinkler System', 'Firewall(s)', 'Gated Community', 'Gated with Guard', 'Guarded', 'Resident Manager', 'Security Lights', 'Security System', 'Smoke Detector(s)', 'Window Bars', 'Wired for Alarm System'];
    public $parkings                 = ['None', 'Assigned', 'Auto Driveway Gate', 'Boat', 'Built-In Storage', 'Carport', 'Attached Carport', 'Detached Carport', 'Circular Driveway', 'Community Structure', 'Controlled Entrance', 'Converted Garage', 'Covered', 'Deck', 'Direct Garage Access', 'Driveway', 'Asphalt', 'Driveway - Brick', 'Driveway - Combination', 'Concrete', 'Gravel', 'Paved', 'Unpaved', 'Driveway Blind', 'Driveway Down Slope From Street', 'Driveway Level', 'Driveway Up Slope From Street', 'Garage', 'Garage Faces Front', 'Garage Faces Rear', 'Garage Faces Side', 'Garage - Single Door', 'Garage - Three Door', 'Garage - Two Door', 'Garage Door Opener', 'Gated', 'Golf Cart Garage', 'Guarded', 'Guest', 'Heated Garage', 'Metered', 'No Driveway', 'Off Site', 'Off Street', 'On Site', 'Other', 'Oversized', 'Parking Space', 'Permit Required', 'Porte-Cochere', 'Private', 'Public', 'Pull-through', 'RV Access/Parking', 'RV Covered', 'RV Garage', 'RV Gated', 'RV Hook-Ups', 'RV Potential', 'See Remarks', 'Shared Driveway', 'Side by Side', 'Street', 'Structure', 'Subterranean', 'Tandem Covered', 'Tandem Garage', 'Tandem Uncovered', 'Unassigned', 'Uncovered', 'Valet', 'Workshop in Garage', 'Electric Vehicle Charging Station(s)'];
    public $spa_features             = ['None', 'Private', 'Association', 'Community', 'Above Ground', 'Bath', 'Fiberglass', 'Gunite', 'Heated', 'In Ground', 'No Permits', 'Permits', 'Roof Top', 'See Remarks', 'Solar Heated', 'Vinyl'];
    public $common_walls             = ['1 Common Wall', '2+ Common Walls', 'End Unit', 'No Common Walls', 'No One Above', 'No One Below'];
    public $construction_materials   = ['Adobe', 'Alcan', 'Aluminum Siding', 'Asbestos', 'Asphalt', 'Block', 'Blown-In Insulation', 'Board & Batten Siding', 'Brick', 'Brick Veneer', 'Cedar', 'Cellulose Insulation', 'Cement Siding', 'Clapboard', 'Concrete', 'Drywall Walls', 'Ducts Professionally Air-Sealed', 'Fiber Cement', 'Fiberglass Siding', 'Flagstone', 'Frame', 'Glass', 'Hardboard', 'HardiPlank Type', 'ICFs (Insulated Concrete Forms)', 'Lap Siding', 'Log', 'Log Siding', 'Masonite', 'Metal Siding', 'Natural Building', 'NES Insulation Pkg', 'Other', 'Plaster', 'Radiant Barrier', 'Rammed Earth', 'Redwood Siding', 'Shake Siding', 'Shingle Siding', 'Slump Block', 'Spray Foam Insulation', 'Steel', 'Steel Siding', 'Stone', 'Stone Veneer', 'Straw', 'Stucco', 'Synthetic Stucco', 'TVA Insulation Pkg', 'Unknown', 'Vertical Siding', 'Vinyl Siding', 'Wood Siding'];
    public $roofs                    = ['None', 'Asbestos Shingle', 'Asphalt', 'Bahama', 'Barrel', 'Bitumen', 'Bituthene', 'Clay', 'Common Roof', 'Composition', 'Concrete', 'Copper', 'Elastomeric', 'Fiberglass', 'Fire Retardant', 'Flat', 'Flat Tile', 'Foam', 'Green Roof', 'Mansard', 'Membrane', 'Metal', 'Mixed', 'Other', 'Reflective', 'Ridge Vents', 'Rolled/Hot Mop', 'See Remarks', 'Shake', 'Shingle', 'Slate', 'Spanish Tile', 'Stone', 'Synthetic', 'Tar/Gravel', 'Tile', 'Wood'];
    public $foundation_details       = ['None', 'Block', 'Brick/Mortar', 'Combination', 'Concrete Perimeter', 'Permanent', 'Pier Jacks', 'Pillar/Post/Pier', 'Quake Bracing', 'Raised', 'See Remarks', 'Seismic Tie Down', 'Slab', 'Stacked Block', 'Stone', 'Tie Down'];
    public $waterfront_features      = ['Across the Road from Lake/Ocean', 'Bay Front', 'Beach Access', 'Beach Front', 'Canal Front', 'Creek', 'Fishing in Community', 'Includes Dock', 'Lagoon', 'Lake', 'Lake Front', 'Lake Privileges', 'Marina in Community', 'Navigable Water', 'Ocean Access', 'Ocean Front', 'Ocean Side of Freeway', 'Ocean Side Of Highway 1', 'Pond', 'Reservoir in Community', 'River Front', 'Sea Front', 'Seawall', 'Stream', 'Waterfront With Home Across Road'];
    public $patio_and_porch_features = ['None', 'Arizona Room', 'Brick', 'Cabana', 'Concrete', 'Covered', 'Deck', 'Enclosed', 'Enclosed Glass Porch', 'Lanai', 'Patio', 'Patio Open', 'Porch', 'Front Porch', 'Rear Porch', 'Roof Top', 'Screened', 'Screened Porch', 'See Remarks', 'Slab', 'Stone', 'Terrace', 'Tile', 'Wood', 'Wrap Around'];
    public $lot_features             = ['0-1 Unit/Acre', '2-5 Units/Acre', '6-10 Units/Acre', '11-15 Units/Acre', '16-20 Units/Acre', '21-25 Units/Acre', '26-30 Units/Acre', '31-35 Units/Acre', '36-40 Units/Acre', 'Agricultural', 'Agricultural - Dairy', 'Agricultural - Other', 'Agricultural - Row/Crop', 'Agricultural - Tree/Orchard', 'Agricultural - Vine/Vineyard', 'Back Yard', 'Bluff', 'Close to Clubhouse', 'Corner Lot', 'Corners Marked', 'Cul-De-Sac', 'Desert Back', 'Desert Front', 'Sloped Down', 'Front Yard', 'Garden', 'Gentle Sloping', 'Greenbelt', 'Horse Property', 'Horse Property Improved', 'Horse Property Unimproved', 'Landscaped', 'Lawn', 'Level with Street', 'Lot 10000-19999 Sqft', 'Lot 20000-39999 Sqft', 'Lot 6500-9999', 'Lot Over 40000 Sqft', 'Flag Lot', 'Irregular Lot', 'Rectangular Lot', 'Level', 'Misting System', 'Near Public Transit', 'No Landscaping', 'On Golf Course', 'Over 40 Units/Acre', 'Park Nearby', 'Pasture', 'Patio Home', 'Paved', 'Percolate', 'Ranch', 'Rocks', 'Rolling Slope', 'Secluded', 'Sprinkler System', 'Sprinklers Drip System', 'Sprinklers In Front', 'Sprinklers In Rear', 'Sprinklers Manual', 'Sprinklers None', 'Sprinklers On Side', 'Sprinklers Timer', 'Steep Slope', 'Tear Down', 'Treed Lot', 'Up Slope from Street', 'Utilities - Overhead', 'Value In Land', 'Walkstreet', 'Yard', 'Zero Lot Line'];
    public $property_conditions      = ['Additions/Alterations', 'Building Permit', 'Fixer', 'Repairs Cosmetic', 'Repairs Major', 'Termite Clearance', 'Turnkey', 'Under Construction', 'Updated/Remodeled'];
    public $sewers                   = ['None', 'Aerobic Septic', 'Cesspool', 'Conventional Septic', 'Engineered Septic', 'Holding Tank', 'Mound Septic', 'Other', 'Perc Test On File', 'Perc Test Required', 'Private Sewer', 'Public Sewer', 'Septic Type Unknown', 'Sewer Applied for Permit', 'Sewer Assessments', 'Sewer On Bond', 'Sewer Paid', 'Shared Septic', 'Soils Analysis Septic', 'Unknown'];
    public $water_sources            = ['None', 'Agricultural Well', 'Cistern', 'Other', 'Private', 'Public', 'See Remarks', 'Shared Well', 'Well'];
    public $architectural_styles     = ['Bungalow', 'Cape Cod', 'Colonial', 'Contemporary', 'Cottage', 'Craftsman', 'Custom Built', 'English', 'French', 'Georgian', 'Log', 'Mediterranean', 'Mid Century Modern', 'Modern', 'Ranch', 'See Remarks', 'Shotgun', 'Spanish', 'Traditional', 'Tudor', 'Victorian'];
    public $community_features       = ['Biking', 'BLM/National Forest', 'Curbs', 'Dog Park', 'Fishing', 'Foothills', 'Golf', 'Hiking', 'Gutters', 'Lake', 'Horse Trails', 'Park', 'Hunting', 'Watersports', 'Military Land', 'Mountainous', 'Preserve/Public Land', 'Ravine', 'Stable(s)', 'Rural', 'Sidewalks', 'Storm Drains', 'Street Lights', 'Suburban', 'Urban', 'Valley'];
    public $road_frontage_types      = ['Access is Seasonal', 'Alley', 'City Street', 'Country Road', 'County Road', 'Highway', 'Private Road'];
    public $road_surface_types       = ['Alley Paved', 'Gravel', 'Maintained', 'Not Maintained', 'Paved', 'Unpaved'];
    public $disclosures              = ['Accessory Dwelling Unit', '3rd Party Rights', 'Bankruptcy', 'Beach Rights', 'Cautions Call Agent', "CC And R's", 'City Inspection Required', 'Coastal Commission Restrictions', 'Coastal Zone', 'Conditional Use Permit', 'Court Confirmation', 'Death On Property < 3 yrs', 'Earthquake Insurance Available', 'Easements', 'Environmental Restrictions', 'Exclusions Call Agent', 'Flood Insurance Required', 'Flood Zone', 'HERO/PACE Loan', 'Historical', 'Home Warranty', 'Homeowners Association', 'Incorporated', 'LA/Owner Related', 'Licensed Vacation Rental', 'Listing Broker Advantage', 'Manufactured Homes Allowed', 'Methane Gas', 'Mineral Rights', 'Moratorium', 'No Lake Rights', 'Oil Rights', 'Open Space Restrictions', 'Pet Restrictions', 'Principal Is RE Licensed', 'Private Transfer Taxes', 'Property Report', 'REAP', 'Redevelopment Area', 'Rent Control', 'Section 8 Approved', 'Seismic Hazard', 'Seller Will Pay Sec. 1 Termite', 'Slide Zone', 'Special Study Area', 'Subject To Estate Ruling', 'Tenants In Common - DRE Pink', 'Tenants In Common - DRE White', 'Unincorporated', 'Water Rights', 'Well Log Available'];
    public $exterior_features        = ['Awning(s)', 'Barbecue Private', 'Boat Lift', 'Boat Slip', 'Corral', 'Dock Private', 'Kennel', 'Koi Pond', 'Lighting', 'Pier', 'Rain Gutters', 'Satellite Dish', 'Stable', 'TV Antenna'];
    public $other_structures         = ['Airplane Hangar', 'Aviary', 'Barn(s)', 'Gazebo', 'Greenhouse', 'Guest House', 'Guest House Attached', 'Guest House Detached', 'Outbuilding', 'Sauna Private', 'Second Garage', 'Second Garage Attached', 'Second Garage Detached', 'Shed(s)', 'Sport Court Private', 'Storage', 'Tennis Court Private', 'Two On A Lot', 'Workshop'];
    public $window_features          = ['Atrium', 'Bay Window(s)', 'Blinds', 'Casement Windows', 'Custom Covering', 'Double Pane Windows', 'Drapes', 'ENERGY STAR Qualified Windows', 'French/Mullioned', 'Garden Window(s)', 'Insulated Windows', 'Jalousies/Louvered', 'Low Emissivity Windows', 'Palladian', 'Plantation Shutters', 'Roller Shields', 'Screens', 'Shutters', 'Skylight(s)', 'Solar Screens', 'Solar Tinted Windows', 'Stained Glass', 'Storm Window(s)', 'Tinted Windows', 'Triple Pane Windows', 'Wood Frames'];

}